### ISSUE TITLE
Error running example_usage

### ISSUE THREAD

**Issue by vpKumaravel** [NadineJac/gaitEEGfootprint#1]
Hello Nadine (@NadineJac)!

Thanks for making the code and sample data available.

I have git cloned the repository and downloaded the data and kept them in the same folder as the code.

While running the example_usage.mlx, I ran into an issue, which is described in the screenshot below:

![image](https://github.com/NadineJac/gaitEEGfootprint/assets/48288235/4688ca76-ed0e-4dee-a710-babdb138ed75)

Please let me know how to fix this!

Best,
Velu

**Comment by NadineJac** [comment]
I misspecified the fields names in the example_usage.mlx.  neckChanL was stored in param.E insted of params.D. Should work now.

If you have Time-frequency-transformed data already, I would advide you to use the lite version, in which feature G (sourceActivity, requiering brainstorm, not parcticulartly sensitive) is dropped and normalization is optimized. Please find the details here: https://doi.org/10.3389%2Ffspor.2022.945341 section Materials and methods/Statistical analysis/Neurophysiological analysis
